services:
  fastapi_server:
    build: .
    container_name: fastapi_server
    image: fastapi_server
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server