site_name: TFM Cybersecurity Lab Guides
site_description: Interactive Cybersecurity Laboratory Guides for ARP & DNS Spoofing, Network Security Testing and Penetration Testing in Docker Environments
site_author: Rodrigo Calero Albarrán
site_url: https://yourdomain.local/

theme:
  name: material
  language: en
  # logo: assets/logo.png
  # favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
      name: GitHub Repository
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/
      name: Docker Hub

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

extra_css:
  - stylesheets/extra.css
  - stylesheets/cards.css
  - stylesheets/animations.css
  - stylesheets/interactive.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mermaid.js
  - stylesheets/interactivity.js

nav:
  - Home: 
    - index.md
    - Getting Started: docker.md
  - Laboratories:
    - "Lab 1: ARP & DNS Spoofing": lab1.md
  - Resources:
    - Docker Setup: docker.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true
      title: Page contents
      permalink_title: Anchor link to this section
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: your-username
      repo: TFM-Labos
